blank_issues_enabled: false
contact_links:
  - name: Have a question?
    url: https://github.com/thorwebdev/nextjs-subscription-payments/discussions?discussions_q=category%3AQ%26A
    about: Ask questions and discuss with other community members.
